# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: http://atodogas.petrolina.com.br
title: A Todo Gás
email: atodogas.petrolina@domain.com
author: André Mendonça
description: Revenda de Água e Gás Ultragaz
copyright: 'Copyright &copy; 2017 A Todo Gás. Todos os direitos reservados.'

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
  - title: (87) 98852-8090
    icons: ['phone', 'whatsapp']
  - title: (87) 99651-8477
    icons: ['phone']
  - title: facebook
    icons: ['facebook']
    url: https://fb.me/atodogas.petrolina/
